### ISSUE TITLE
MOTD not showing

### ISSUE THREAD

**Issue by TheShihan** [QwazyWabbitWOS/lithium#1]
I have a motd.txt in my mod ("lithium") directory with the content "test" (all on 1 line). I add this to the server config:
set motd "motd.txt"

But the MOTD does not appear. Only the default text "Matt "whitefang" ayres...." appears but not the text from my config.

I also tried it by using_
set motd "motd"

(without extension). Or using another text. After everychange I restart the server to make sure that the new confguration should be loaded, still the MOTD does not appear.

Does anybody know that the issue could be? Where does the mod look for this file (I guess inside the mod directory) and does the file need to have an extension?

**Comment by QwazyWabbitWOS** [comment]
You have it correct. The default name is "motd.txt" and the default path is the mod directory, "lithium". The full path to the file would be lithium/motd.txt and it is case-sensitive on Linux so be sure to take that into account. 

The text appears in my q2pro client in the lower left portion of the screen after joining a team. It shows up just above the Lithium version number and the credit to Matt. It doesn't print to center or show up in the console screen but it disappears when you shoot or move and reappears if you pause and stand still. It doesn't centerprint or splash like some other mods.

The text of the file is reloaded at every showing so you don't have to restart the server to update it.


![quake000](https://github.com/user-attachments/assets/3fe26a0b-8dc5-4dc3-82f9-21f4c125c674)

**Comment by TheShihan** [comment]
Unfortunately my custom motd does not appear when I join a team. The standard MOTD appears when I don't move for some seconds, but my custom part is still missing. There is no error in the log. I checked also the case, all names match up.
May I rebuild the game from this repo and try it again.

**Update:** even with the version from this repo the MOTD does not show up. Would you mind sending me your example MOTD from the screenshot? Maybe it's something like false line endings or encoding.

**Comment by QwazyWabbitWOS** [comment]
Here is my motd.txt.

[motd.txt](https://github.com/user-attachments/files/16843526/motd.txt)

It certainly is a mystery why it isn't working for you. Yes, there's no error reporting when it doesn't find a motd file. Soft error reporting is pretty thin in all these mods, frankly.

The function that performs the loading of the motd is `GetMOTD` so you could set a breakpoint at line 260 of l_display.c to see that motd->string is the correct file name and then step to see that it successfully opened it and step a few more times to see that it reads the lines. The lines must be less than 256 chars long.

**Comment by TheShihan** [comment]
The server runs inside a linux docker container and I don't know how to remote debug this (if even possible). But I was able to add some logging statements to the GetMOTD and some other functions and I see that it tried to load the file from the wrong path:
`Attempting to load MOTD file from absolute path: /usr/share/q2pro/lithium/motd.txt `

But inside the container the mod related files (especially the "gamex86_64.so") are under `/home/quake2-server/.q2pro/lithium`.
So I guess, this is some q2pro related issue? It works if I add a another volume as with the motd.txt (and also "maps.lst") inside /usr/share/q2pro/lithium - map voting was also not possible before and now it uses the correct maps from "maps.lst".

I opened a question in the q2pro repo: https://github.com/skullernet/q2pro/issues/354

**Comment by QwazyWabbitWOS** [comment]
I suspected it might be a Linux issue. Quake II was originally targeted for Windows and the Linux code antedates the original implementation and the code that was released in the source releases was that "cleaned up" code.

From the beginning, with IdSoftware code, the engine binary was placed in the root of the Quake II tree, being ~/quake2/, this roots the working directory properly and the gamedir is then rooted as ~/quake2/gamedir. The modern policy of rooting the binary in /usr/bin or /usr/share changes all that and confuses the mods. I do not think this is unique to Lithium. Hosted servers all seem to root their users the old-fashioned way, perhaps by necessity. I'm not sure about the primary motive for the change but I suspect it's all about disk space and resource sharing. I don't know of any substantial security benefits from the practice. I've never implemented a docker space myself so I have no personal experience with it.

I'm looking at the OpenFFA code to see if it can be adapted to Lithium without creating a dependency on running it exclusively with q2proded.

**Comment by TheShihan** [comment]
I was able to solve it by changing the working directory but yes, maybe you can make changes to this mod so that this would not be necessary.

**Comment by QwazyWabbitWOS** [comment]
I have patched the change and tested with q2proded and r1q2 to test the `fs_gamedir` path as well as the `basedir` `gamedir` pathway. Let me know how it works in your docker instance. If it works with and without the working directory hack then I'll consider it closed. 

As for the /home/quake2-server/.q2pro/baseq2 path mentioned in your #354 issue with skuller. I'm not sure why it needs to be explicit. That path should come "free" with the filesystem from the engine. The Q2 FS is flat with respect to all the resources and the mod folders override the baseq2 for resources that bear the same file name. Perhaps the way Lithium used it in the `file_gamedir` function was the cause of that.

**Comment by TheShihan** [comment]
I have tested your new version with my previous version of the docker image where the working directory is still /usr/share/q2pro and it worked. It correctly loaded the motd.txt and maps.lst from the correct folder.

I will probably still keep the working directory fix in my dockerfile (or make it changeable through an environment variable in a later version) to support other mods that don't have this fix for q2pro.

**Comment by QwazyWabbitWOS** [comment]
Sounds good. I'll update the version number now (since I forgot to do that) and make the corresponding change in li2mod as well. Looking at the Lithium code and some other mods, it looks like the reference to baseq2 was erroneous in Lithium and the technique was susceptible to this issue. It should have been taking the path from the `game` cvar in the first place since that's set either in the command line or early in the server config when the mod is launched. I've never seen anyone encounter this in any mods until now.

**Comment by TheShihan** [comment]
What is the difference between this repo and [li2mod](https://github.com/QwazyWabbitWOS/li2mod)?

**Comment by QwazyWabbitWOS** [comment]
The li2mod is just a different fork. In my collection the primary difference is some formatting and perhaps some library calls. It also doesn't use the internal strlcpy or strlcat functions. I think the lithium repo might be closer to WhiteFang's original, historically, but I'm not sure.

**Comment by TheShihan** [comment]
hmm, okay. Personally I think it is very confusing: as a server admin I was searching for the latest lithium II mod that should be used nowadays:
Here on github is the repo of the original creator:

- https://github.com/mattayres/li2mod/tree/master/lithium (original, but no changes since 15 years) (version 1.31)

Then we have your two repos which are are fork from the original one (well li2mod at least appears to be a fork):
- https://github.com/QwazyWabbitWOS/li2mod (fork of the original https://github.com/mattayres/li2mod/tree/master/lithium, but has some formatting changes, etc.) (version 1.32-beta2?)
- https://github.com/QwazyWabbitWOS/lithium (more closer to the orginial?) (version 1.32, now)

Maybe this could be made more clear in the readmes, what the purpose of each of your repos is and the relation to the original. I wonder if it would be a good idea to have different versioning for the two newer versions/repos?

Also it would be nice if history.txt could reflect the latest changes with date and author.

**Comment by QwazyWabbitWOS** [comment]
To be pefectly frank, I'm a little offended by that last comment. The last time I worked on this was 9 months ago and prior to that it was more than a year ago on a project of mine that is more than 4 years old.

I've long since forgotten everything I've done and the reasons but it's all recorded by Git, line by line in complete detail for anyone to see and you are perfectly free to browse all the repositories online or to clone all three and diff them yourself. Git also records authorship annotations visible in the Blame function. Keeping a separate history or change file would be prone to error and redundant. Even Matt admits to missing things in his history.txt file and I see no reason to add my own errors and omissions to that file.

The primary motive of both projects was to implement x64-clean binaries for my own use under VS2019 and VS2022. The Ayres fork is for VS2010 converted, I believe, from VC++ 6.0 and Linux 2.0. The 1.32-beta2 tag is from Whitefang and since the game is essentially only different in build type and internals and not a change of the game functionality I didn't feel compelled to update that tag. Furthermore, if you were to clone Whitefang's repo and attempt to build it you will immediately discover that it won't build on current versions of Linux and GCC.

This fork, `lithium` was created and made public before the https://github.com/mattayres/li2mod/tree/master/lithium was public. It was derived from sources downloaded from the Lithium web site, not a fork from anything. I have never bothered to take the time to try to diff the WhiteFang source. My purpose was to update the C code to more contemporary standards, elevate the error reporting and get rid of some problematic usages like `strdup` and to obtain updated binaries for my own servers for both Linux and Windows. My policy has been to preserve the sources of various Quake II mods to prevent them from being lost forever the way so many mods have been lost because they were kept closed.

Your original issue with the game path discovery was valid and it's traceable to a bug in the original code. I responded to your issue in a timely fashion and fixed it in both of my forks. You're welcome.

Feel free to use whichever fork best serves your purposes. That's what GitHub is all about.

**Comment by TheShihan** [comment]
I'm sorry, it was not my intention to offend you. I was just confused about the different repositories and how they came to be.
I'm glad you took the time to help me and thank you for your quick feedback.

**Comment by QwazyWabbitWOS** [comment]
I accept the apology and I can see why there was some confusion. There was a 1.25-R1 version that Tastyspleen uses that fixed several vulnerabilities in 2007 but I never found the sources for it. In 2010 WF merged them with his version to produce the 1.30 version and successors so there's a lot of history missing for that period.

**Comment by QwazyWabbitWOS** [comment]
I took another look at the code and decided to fix some bugs I found. Comparing li2mod and lithium repositories, I decided to make my changes in my li2mod fork rather than the lithium fork. I may delete or hide this one rather than make changes here. The li2mod is direct descendant from Matt's original on GitHub. I'm really not sure where this repository inherits from but I think I created it from a local copy of the 1.31 sources from a zip file I obtained from the quake2lithium.com website but that site is now defunct and it appears to be archived here: https://quake2lithium.github.io/ and https://quake2.lithium.com/
I took your suggestion about the history.txt file and documented most of my changes there. Git does a better job of recording changes than any manual history. Like Matt, I forget to note changes as I go along. :)

All changes are now in the https://github.com/QwazyWabbitWOS/li2mod repo.
